/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesTeachingKidsOnlinePrivacyRouteImport } from './routes/resources.teaching-kids-online-privacy'
import { Route as ResourcesTalkingToKidsAboutAiRouteImport } from './routes/resources.talking-to-kids-about-ai'
import { Route as ResourcesSettingDigitalBoundariesRouteImport } from './routes/resources.setting-digital-boundaries'
import { Route as ResourcesHealthyScreenTimeHabitsRouteImport } from './routes/resources.healthy-screen-time-habits'
import { Route as ResourcesFamilyTechnologyAgreementsRouteImport } from './routes/resources.family-technology-agreements'
import { Route as ResourcesFamilyTechnologyAgreementTemplateRouteImport } from './routes/resources.family-technology-agreement-template'
import { Route as ResourcesFamilyDigitalBoundariesPlannerRouteImport } from './routes/resources.family-digital-boundaries-planner'
import { Route as ResourcesDownloadsRouteImport } from './routes/resources.downloads'
import { Route as ResourcesChatbotSafetyForFamiliesRouteImport } from './routes/resources.chatbot-safety-for-families'
import { Route as ResourcesChatbotSafetyChecklistRouteImport } from './routes/resources.chatbot-safety-checklist'
import { Route as ResourcesAppPrivacyReviewChecklistRouteImport } from './routes/resources.app-privacy-review-checklist'
import { Route as ResourcesAgeByAgeAiConversationGuideRouteImport } from './routes/resources.age-by-age-ai-conversation-guide'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AppWellnessRouteImport } from './routes/_app/wellness'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppFiltersRouteImport } from './routes/_app/filters'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContractsRouteImport } from './routes/_app/contracts'
import { Route as AppBehaviorAlertsRouteImport } from './routes/_app/behavior-alerts'
import { Route as AppAppMonitoringRouteImport } from './routes/_app/app-monitoring'
import { Route as AppWellnessIndexRouteImport } from './routes/_app/wellness.index'
import { Route as ResourcesDownloadsPrintAllRouteImport } from './routes/resources.downloads.print-all'
import { Route as AppWellnessReportIdRouteImport } from './routes/_app/wellness.$reportId'
import { Route as AppChildChildIdRouteImport } from './routes/_app/child.$childId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesTeachingKidsOnlinePrivacyRoute =
  ResourcesTeachingKidsOnlinePrivacyRouteImport.update({
    id: '/teaching-kids-online-privacy',
    path: '/teaching-kids-online-privacy',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesTalkingToKidsAboutAiRoute =
  ResourcesTalkingToKidsAboutAiRouteImport.update({
    id: '/talking-to-kids-about-ai',
    path: '/talking-to-kids-about-ai',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesSettingDigitalBoundariesRoute =
  ResourcesSettingDigitalBoundariesRouteImport.update({
    id: '/setting-digital-boundaries',
    path: '/setting-digital-boundaries',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesHealthyScreenTimeHabitsRoute =
  ResourcesHealthyScreenTimeHabitsRouteImport.update({
    id: '/healthy-screen-time-habits',
    path: '/healthy-screen-time-habits',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesFamilyTechnologyAgreementsRoute =
  ResourcesFamilyTechnologyAgreementsRouteImport.update({
    id: '/family-technology-agreements',
    path: '/family-technology-agreements',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesFamilyTechnologyAgreementTemplateRoute =
  ResourcesFamilyTechnologyAgreementTemplateRouteImport.update({
    id: '/family-technology-agreement-template',
    path: '/family-technology-agreement-template',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesFamilyDigitalBoundariesPlannerRoute =
  ResourcesFamilyDigitalBoundariesPlannerRouteImport.update({
    id: '/family-digital-boundaries-planner',
    path: '/family-digital-boundaries-planner',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesDownloadsRoute = ResourcesDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => ResourcesRoute,
} as any)
const ResourcesChatbotSafetyForFamiliesRoute =
  ResourcesChatbotSafetyForFamiliesRouteImport.update({
    id: '/chatbot-safety-for-families',
    path: '/chatbot-safety-for-families',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesChatbotSafetyChecklistRoute =
  ResourcesChatbotSafetyChecklistRouteImport.update({
    id: '/chatbot-safety-checklist',
    path: '/chatbot-safety-checklist',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesAppPrivacyReviewChecklistRoute =
  ResourcesAppPrivacyReviewChecklistRouteImport.update({
    id: '/app-privacy-review-checklist',
    path: '/app-privacy-review-checklist',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesAgeByAgeAiConversationGuideRoute =
  ResourcesAgeByAgeAiConversationGuideRouteImport.update({
    id: '/age-by-age-ai-conversation-guide',
    path: '/age-by-age-ai-conversation-guide',
    getParentRoute: () => ResourcesRoute,
  } as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWellnessRoute = AppWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFiltersRoute = AppFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppBehaviorAlertsRoute = AppBehaviorAlertsRouteImport.update({
  id: '/behavior-alerts',
  path: '/behavior-alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAppMonitoringRoute = AppAppMonitoringRouteImport.update({
  id: '/app-monitoring',
  path: '/app-monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppWellnessIndexRoute = AppWellnessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWellnessRoute,
} as any)
const ResourcesDownloadsPrintAllRoute =
  ResourcesDownloadsPrintAllRouteImport.update({
    id: '/print-all',
    path: '/print-all',
    getParentRoute: () => ResourcesDownloadsRoute,
  } as any)
const AppWellnessReportIdRoute = AppWellnessReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AppWellnessRoute,
} as any)
const AppChildChildIdRoute = AppChildChildIdRouteImport.update({
  id: '/child/$childId',
  path: '/child/$childId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app-monitoring': typeof AppAppMonitoringRoute
  '/behavior-alerts': typeof AppBehaviorAlertsRoute
  '/contracts': typeof AppContractsRoute
  '/dashboard': typeof AppDashboardRoute
  '/filters': typeof AppFiltersRoute
  '/settings': typeof AppSettingsRoute
  '/wellness': typeof AppWellnessRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/resources/age-by-age-ai-conversation-guide': typeof ResourcesAgeByAgeAiConversationGuideRoute
  '/resources/app-privacy-review-checklist': typeof ResourcesAppPrivacyReviewChecklistRoute
  '/resources/chatbot-safety-checklist': typeof ResourcesChatbotSafetyChecklistRoute
  '/resources/chatbot-safety-for-families': typeof ResourcesChatbotSafetyForFamiliesRoute
  '/resources/downloads': typeof ResourcesDownloadsRouteWithChildren
  '/resources/family-digital-boundaries-planner': typeof ResourcesFamilyDigitalBoundariesPlannerRoute
  '/resources/family-technology-agreement-template': typeof ResourcesFamilyTechnologyAgreementTemplateRoute
  '/resources/family-technology-agreements': typeof ResourcesFamilyTechnologyAgreementsRoute
  '/resources/healthy-screen-time-habits': typeof ResourcesHealthyScreenTimeHabitsRoute
  '/resources/setting-digital-boundaries': typeof ResourcesSettingDigitalBoundariesRoute
  '/resources/talking-to-kids-about-ai': typeof ResourcesTalkingToKidsAboutAiRoute
  '/resources/teaching-kids-online-privacy': typeof ResourcesTeachingKidsOnlinePrivacyRoute
  '/resources/': typeof ResourcesIndexRoute
  '/child/$childId': typeof AppChildChildIdRoute
  '/wellness/$reportId': typeof AppWellnessReportIdRoute
  '/resources/downloads/print-all': typeof ResourcesDownloadsPrintAllRoute
  '/wellness/': typeof AppWellnessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/app-monitoring': typeof AppAppMonitoringRoute
  '/behavior-alerts': typeof AppBehaviorAlertsRoute
  '/contracts': typeof AppContractsRoute
  '/dashboard': typeof AppDashboardRoute
  '/filters': typeof AppFiltersRoute
  '/settings': typeof AppSettingsRoute
  '/c/$token': typeof CTokenRoute
  '/resources/age-by-age-ai-conversation-guide': typeof ResourcesAgeByAgeAiConversationGuideRoute
  '/resources/app-privacy-review-checklist': typeof ResourcesAppPrivacyReviewChecklistRoute
  '/resources/chatbot-safety-checklist': typeof ResourcesChatbotSafetyChecklistRoute
  '/resources/chatbot-safety-for-families': typeof ResourcesChatbotSafetyForFamiliesRoute
  '/resources/downloads': typeof ResourcesDownloadsRouteWithChildren
  '/resources/family-digital-boundaries-planner': typeof ResourcesFamilyDigitalBoundariesPlannerRoute
  '/resources/family-technology-agreement-template': typeof ResourcesFamilyTechnologyAgreementTemplateRoute
  '/resources/family-technology-agreements': typeof ResourcesFamilyTechnologyAgreementsRoute
  '/resources/healthy-screen-time-habits': typeof ResourcesHealthyScreenTimeHabitsRoute
  '/resources/setting-digital-boundaries': typeof ResourcesSettingDigitalBoundariesRoute
  '/resources/talking-to-kids-about-ai': typeof ResourcesTalkingToKidsAboutAiRoute
  '/resources/teaching-kids-online-privacy': typeof ResourcesTeachingKidsOnlinePrivacyRoute
  '/resources': typeof ResourcesIndexRoute
  '/child/$childId': typeof AppChildChildIdRoute
  '/wellness/$reportId': typeof AppWellnessReportIdRoute
  '/resources/downloads/print-all': typeof ResourcesDownloadsPrintAllRoute
  '/wellness': typeof AppWellnessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_app/app-monitoring': typeof AppAppMonitoringRoute
  '/_app/behavior-alerts': typeof AppBehaviorAlertsRoute
  '/_app/contracts': typeof AppContractsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/filters': typeof AppFiltersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/wellness': typeof AppWellnessRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/resources/age-by-age-ai-conversation-guide': typeof ResourcesAgeByAgeAiConversationGuideRoute
  '/resources/app-privacy-review-checklist': typeof ResourcesAppPrivacyReviewChecklistRoute
  '/resources/chatbot-safety-checklist': typeof ResourcesChatbotSafetyChecklistRoute
  '/resources/chatbot-safety-for-families': typeof ResourcesChatbotSafetyForFamiliesRoute
  '/resources/downloads': typeof ResourcesDownloadsRouteWithChildren
  '/resources/family-digital-boundaries-planner': typeof ResourcesFamilyDigitalBoundariesPlannerRoute
  '/resources/family-technology-agreement-template': typeof ResourcesFamilyTechnologyAgreementTemplateRoute
  '/resources/family-technology-agreements': typeof ResourcesFamilyTechnologyAgreementsRoute
  '/resources/healthy-screen-time-habits': typeof ResourcesHealthyScreenTimeHabitsRoute
  '/resources/setting-digital-boundaries': typeof ResourcesSettingDigitalBoundariesRoute
  '/resources/talking-to-kids-about-ai': typeof ResourcesTalkingToKidsAboutAiRoute
  '/resources/teaching-kids-online-privacy': typeof ResourcesTeachingKidsOnlinePrivacyRoute
  '/resources/': typeof ResourcesIndexRoute
  '/_app/child/$childId': typeof AppChildChildIdRoute
  '/_app/wellness/$reportId': typeof AppWellnessReportIdRoute
  '/resources/downloads/print-all': typeof ResourcesDownloadsPrintAllRoute
  '/_app/wellness/': typeof AppWellnessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/editorial-policy'
    | '/faq'
    | '/privacy'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/app-monitoring'
    | '/behavior-alerts'
    | '/contracts'
    | '/dashboard'
    | '/filters'
    | '/settings'
    | '/wellness'
    | '/c/$token'
    | '/resources/age-by-age-ai-conversation-guide'
    | '/resources/app-privacy-review-checklist'
    | '/resources/chatbot-safety-checklist'
    | '/resources/chatbot-safety-for-families'
    | '/resources/downloads'
    | '/resources/family-digital-boundaries-planner'
    | '/resources/family-technology-agreement-template'
    | '/resources/family-technology-agreements'
    | '/resources/healthy-screen-time-habits'
    | '/resources/setting-digital-boundaries'
    | '/resources/talking-to-kids-about-ai'
    | '/resources/teaching-kids-online-privacy'
    | '/resources/'
    | '/child/$childId'
    | '/wellness/$reportId'
    | '/resources/downloads/print-all'
    | '/wellness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/editorial-policy'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/app-monitoring'
    | '/behavior-alerts'
    | '/contracts'
    | '/dashboard'
    | '/filters'
    | '/settings'
    | '/c/$token'
    | '/resources/age-by-age-ai-conversation-guide'
    | '/resources/app-privacy-review-checklist'
    | '/resources/chatbot-safety-checklist'
    | '/resources/chatbot-safety-for-families'
    | '/resources/downloads'
    | '/resources/family-digital-boundaries-planner'
    | '/resources/family-technology-agreement-template'
    | '/resources/family-technology-agreements'
    | '/resources/healthy-screen-time-habits'
    | '/resources/setting-digital-boundaries'
    | '/resources/talking-to-kids-about-ai'
    | '/resources/teaching-kids-online-privacy'
    | '/resources'
    | '/child/$childId'
    | '/wellness/$reportId'
    | '/resources/downloads/print-all'
    | '/wellness'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/auth'
    | '/contact'
    | '/editorial-policy'
    | '/faq'
    | '/privacy'
    | '/resources'
    | '/sitemap.xml'
    | '/terms'
    | '/_app/app-monitoring'
    | '/_app/behavior-alerts'
    | '/_app/contracts'
    | '/_app/dashboard'
    | '/_app/filters'
    | '/_app/settings'
    | '/_app/wellness'
    | '/c/$token'
    | '/resources/age-by-age-ai-conversation-guide'
    | '/resources/app-privacy-review-checklist'
    | '/resources/chatbot-safety-checklist'
    | '/resources/chatbot-safety-for-families'
    | '/resources/downloads'
    | '/resources/family-digital-boundaries-planner'
    | '/resources/family-technology-agreement-template'
    | '/resources/family-technology-agreements'
    | '/resources/healthy-screen-time-habits'
    | '/resources/setting-digital-boundaries'
    | '/resources/talking-to-kids-about-ai'
    | '/resources/teaching-kids-online-privacy'
    | '/resources/'
    | '/_app/child/$childId'
    | '/_app/wellness/$reportId'
    | '/resources/downloads/print-all'
    | '/_app/wellness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CTokenRoute: typeof CTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/teaching-kids-online-privacy': {
      id: '/resources/teaching-kids-online-privacy'
      path: '/teaching-kids-online-privacy'
      fullPath: '/resources/teaching-kids-online-privacy'
      preLoaderRoute: typeof ResourcesTeachingKidsOnlinePrivacyRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/talking-to-kids-about-ai': {
      id: '/resources/talking-to-kids-about-ai'
      path: '/talking-to-kids-about-ai'
      fullPath: '/resources/talking-to-kids-about-ai'
      preLoaderRoute: typeof ResourcesTalkingToKidsAboutAiRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/setting-digital-boundaries': {
      id: '/resources/setting-digital-boundaries'
      path: '/setting-digital-boundaries'
      fullPath: '/resources/setting-digital-boundaries'
      preLoaderRoute: typeof ResourcesSettingDigitalBoundariesRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/healthy-screen-time-habits': {
      id: '/resources/healthy-screen-time-habits'
      path: '/healthy-screen-time-habits'
      fullPath: '/resources/healthy-screen-time-habits'
      preLoaderRoute: typeof ResourcesHealthyScreenTimeHabitsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/family-technology-agreements': {
      id: '/resources/family-technology-agreements'
      path: '/family-technology-agreements'
      fullPath: '/resources/family-technology-agreements'
      preLoaderRoute: typeof ResourcesFamilyTechnologyAgreementsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/family-technology-agreement-template': {
      id: '/resources/family-technology-agreement-template'
      path: '/family-technology-agreement-template'
      fullPath: '/resources/family-technology-agreement-template'
      preLoaderRoute: typeof ResourcesFamilyTechnologyAgreementTemplateRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/family-digital-boundaries-planner': {
      id: '/resources/family-digital-boundaries-planner'
      path: '/family-digital-boundaries-planner'
      fullPath: '/resources/family-digital-boundaries-planner'
      preLoaderRoute: typeof ResourcesFamilyDigitalBoundariesPlannerRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/downloads': {
      id: '/resources/downloads'
      path: '/downloads'
      fullPath: '/resources/downloads'
      preLoaderRoute: typeof ResourcesDownloadsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/chatbot-safety-for-families': {
      id: '/resources/chatbot-safety-for-families'
      path: '/chatbot-safety-for-families'
      fullPath: '/resources/chatbot-safety-for-families'
      preLoaderRoute: typeof ResourcesChatbotSafetyForFamiliesRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/chatbot-safety-checklist': {
      id: '/resources/chatbot-safety-checklist'
      path: '/chatbot-safety-checklist'
      fullPath: '/resources/chatbot-safety-checklist'
      preLoaderRoute: typeof ResourcesChatbotSafetyChecklistRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/app-privacy-review-checklist': {
      id: '/resources/app-privacy-review-checklist'
      path: '/app-privacy-review-checklist'
      fullPath: '/resources/app-privacy-review-checklist'
      preLoaderRoute: typeof ResourcesAppPrivacyReviewChecklistRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/age-by-age-ai-conversation-guide': {
      id: '/resources/age-by-age-ai-conversation-guide'
      path: '/age-by-age-ai-conversation-guide'
      fullPath: '/resources/age-by-age-ai-conversation-guide'
      preLoaderRoute: typeof ResourcesAgeByAgeAiConversationGuideRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wellness': {
      id: '/_app/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof AppWellnessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/filters': {
      id: '/_app/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof AppFiltersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts': {
      id: '/_app/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/behavior-alerts': {
      id: '/_app/behavior-alerts'
      path: '/behavior-alerts'
      fullPath: '/behavior-alerts'
      preLoaderRoute: typeof AppBehaviorAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app-monitoring': {
      id: '/_app/app-monitoring'
      path: '/app-monitoring'
      fullPath: '/app-monitoring'
      preLoaderRoute: typeof AppAppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wellness/': {
      id: '/_app/wellness/'
      path: '/'
      fullPath: '/wellness/'
      preLoaderRoute: typeof AppWellnessIndexRouteImport
      parentRoute: typeof AppWellnessRoute
    }
    '/resources/downloads/print-all': {
      id: '/resources/downloads/print-all'
      path: '/print-all'
      fullPath: '/resources/downloads/print-all'
      preLoaderRoute: typeof ResourcesDownloadsPrintAllRouteImport
      parentRoute: typeof ResourcesDownloadsRoute
    }
    '/_app/wellness/$reportId': {
      id: '/_app/wellness/$reportId'
      path: '/$reportId'
      fullPath: '/wellness/$reportId'
      preLoaderRoute: typeof AppWellnessReportIdRouteImport
      parentRoute: typeof AppWellnessRoute
    }
    '/_app/child/$childId': {
      id: '/_app/child/$childId'
      path: '/child/$childId'
      fullPath: '/child/$childId'
      preLoaderRoute: typeof AppChildChildIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppWellnessRouteChildren {
  AppWellnessReportIdRoute: typeof AppWellnessReportIdRoute
  AppWellnessIndexRoute: typeof AppWellnessIndexRoute
}

const AppWellnessRouteChildren: AppWellnessRouteChildren = {
  AppWellnessReportIdRoute: AppWellnessReportIdRoute,
  AppWellnessIndexRoute: AppWellnessIndexRoute,
}

const AppWellnessRouteWithChildren = AppWellnessRoute._addFileChildren(
  AppWellnessRouteChildren,
)

interface AppRouteChildren {
  AppAppMonitoringRoute: typeof AppAppMonitoringRoute
  AppBehaviorAlertsRoute: typeof AppBehaviorAlertsRoute
  AppContractsRoute: typeof AppContractsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFiltersRoute: typeof AppFiltersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWellnessRoute: typeof AppWellnessRouteWithChildren
  AppChildChildIdRoute: typeof AppChildChildIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppMonitoringRoute: AppAppMonitoringRoute,
  AppBehaviorAlertsRoute: AppBehaviorAlertsRoute,
  AppContractsRoute: AppContractsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFiltersRoute: AppFiltersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWellnessRoute: AppWellnessRouteWithChildren,
  AppChildChildIdRoute: AppChildChildIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ResourcesDownloadsRouteChildren {
  ResourcesDownloadsPrintAllRoute: typeof ResourcesDownloadsPrintAllRoute
}

const ResourcesDownloadsRouteChildren: ResourcesDownloadsRouteChildren = {
  ResourcesDownloadsPrintAllRoute: ResourcesDownloadsPrintAllRoute,
}

const ResourcesDownloadsRouteWithChildren =
  ResourcesDownloadsRoute._addFileChildren(ResourcesDownloadsRouteChildren)

interface ResourcesRouteChildren {
  ResourcesAgeByAgeAiConversationGuideRoute: typeof ResourcesAgeByAgeAiConversationGuideRoute
  ResourcesAppPrivacyReviewChecklistRoute: typeof ResourcesAppPrivacyReviewChecklistRoute
  ResourcesChatbotSafetyChecklistRoute: typeof ResourcesChatbotSafetyChecklistRoute
  ResourcesChatbotSafetyForFamiliesRoute: typeof ResourcesChatbotSafetyForFamiliesRoute
  ResourcesDownloadsRoute: typeof ResourcesDownloadsRouteWithChildren
  ResourcesFamilyDigitalBoundariesPlannerRoute: typeof ResourcesFamilyDigitalBoundariesPlannerRoute
  ResourcesFamilyTechnologyAgreementTemplateRoute: typeof ResourcesFamilyTechnologyAgreementTemplateRoute
  ResourcesFamilyTechnologyAgreementsRoute: typeof ResourcesFamilyTechnologyAgreementsRoute
  ResourcesHealthyScreenTimeHabitsRoute: typeof ResourcesHealthyScreenTimeHabitsRoute
  ResourcesSettingDigitalBoundariesRoute: typeof ResourcesSettingDigitalBoundariesRoute
  ResourcesTalkingToKidsAboutAiRoute: typeof ResourcesTalkingToKidsAboutAiRoute
  ResourcesTeachingKidsOnlinePrivacyRoute: typeof ResourcesTeachingKidsOnlinePrivacyRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesAgeByAgeAiConversationGuideRoute:
    ResourcesAgeByAgeAiConversationGuideRoute,
  ResourcesAppPrivacyReviewChecklistRoute:
    ResourcesAppPrivacyReviewChecklistRoute,
  ResourcesChatbotSafetyChecklistRoute: ResourcesChatbotSafetyChecklistRoute,
  ResourcesChatbotSafetyForFamiliesRoute:
    ResourcesChatbotSafetyForFamiliesRoute,
  ResourcesDownloadsRoute: ResourcesDownloadsRouteWithChildren,
  ResourcesFamilyDigitalBoundariesPlannerRoute:
    ResourcesFamilyDigitalBoundariesPlannerRoute,
  ResourcesFamilyTechnologyAgreementTemplateRoute:
    ResourcesFamilyTechnologyAgreementTemplateRoute,
  ResourcesFamilyTechnologyAgreementsRoute:
    ResourcesFamilyTechnologyAgreementsRoute,
  ResourcesHealthyScreenTimeHabitsRoute: ResourcesHealthyScreenTimeHabitsRoute,
  ResourcesSettingDigitalBoundariesRoute:
    ResourcesSettingDigitalBoundariesRoute,
  ResourcesTalkingToKidsAboutAiRoute: ResourcesTalkingToKidsAboutAiRoute,
  ResourcesTeachingKidsOnlinePrivacyRoute:
    ResourcesTeachingKidsOnlinePrivacyRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CTokenRoute: CTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
