/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as AppWellnessRouteImport } from './routes/_app/wellness'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppFiltersRouteImport } from './routes/_app/filters'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppContractsRouteImport } from './routes/_app/contracts'
import { Route as AppBehaviorAlertsRouteImport } from './routes/_app/behavior-alerts'
import { Route as AppAppMonitoringRouteImport } from './routes/_app/app-monitoring'
import { Route as AppWellnessReportIdRouteImport } from './routes/_app/wellness.$reportId'
import { Route as AppChildChildIdRouteImport } from './routes/_app/child.$childId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWellnessRoute = AppWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppFiltersRoute = AppFiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContractsRoute = AppContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AppRoute,
} as any)
const AppBehaviorAlertsRoute = AppBehaviorAlertsRouteImport.update({
  id: '/behavior-alerts',
  path: '/behavior-alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppAppMonitoringRoute = AppAppMonitoringRouteImport.update({
  id: '/app-monitoring',
  path: '/app-monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppWellnessReportIdRoute = AppWellnessReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AppWellnessRoute,
} as any)
const AppChildChildIdRoute = AppChildChildIdRouteImport.update({
  id: '/child/$childId',
  path: '/child/$childId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app-monitoring': typeof AppAppMonitoringRoute
  '/behavior-alerts': typeof AppBehaviorAlertsRoute
  '/contracts': typeof AppContractsRoute
  '/dashboard': typeof AppDashboardRoute
  '/filters': typeof AppFiltersRoute
  '/settings': typeof AppSettingsRoute
  '/wellness': typeof AppWellnessRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/child/$childId': typeof AppChildChildIdRoute
  '/wellness/$reportId': typeof AppWellnessReportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app-monitoring': typeof AppAppMonitoringRoute
  '/behavior-alerts': typeof AppBehaviorAlertsRoute
  '/contracts': typeof AppContractsRoute
  '/dashboard': typeof AppDashboardRoute
  '/filters': typeof AppFiltersRoute
  '/settings': typeof AppSettingsRoute
  '/wellness': typeof AppWellnessRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/child/$childId': typeof AppChildChildIdRoute
  '/wellness/$reportId': typeof AppWellnessReportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/app-monitoring': typeof AppAppMonitoringRoute
  '/_app/behavior-alerts': typeof AppBehaviorAlertsRoute
  '/_app/contracts': typeof AppContractsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/filters': typeof AppFiltersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/wellness': typeof AppWellnessRouteWithChildren
  '/c/$token': typeof CTokenRoute
  '/_app/child/$childId': typeof AppChildChildIdRoute
  '/_app/wellness/$reportId': typeof AppWellnessReportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app-monitoring'
    | '/behavior-alerts'
    | '/contracts'
    | '/dashboard'
    | '/filters'
    | '/settings'
    | '/wellness'
    | '/c/$token'
    | '/child/$childId'
    | '/wellness/$reportId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app-monitoring'
    | '/behavior-alerts'
    | '/contracts'
    | '/dashboard'
    | '/filters'
    | '/settings'
    | '/wellness'
    | '/c/$token'
    | '/child/$childId'
    | '/wellness/$reportId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/app-monitoring'
    | '/_app/behavior-alerts'
    | '/_app/contracts'
    | '/_app/dashboard'
    | '/_app/filters'
    | '/_app/settings'
    | '/_app/wellness'
    | '/c/$token'
    | '/_app/child/$childId'
    | '/_app/wellness/$reportId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CTokenRoute: typeof CTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wellness': {
      id: '/_app/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof AppWellnessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/filters': {
      id: '/_app/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof AppFiltersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contracts': {
      id: '/_app/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AppContractsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/behavior-alerts': {
      id: '/_app/behavior-alerts'
      path: '/behavior-alerts'
      fullPath: '/behavior-alerts'
      preLoaderRoute: typeof AppBehaviorAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app-monitoring': {
      id: '/_app/app-monitoring'
      path: '/app-monitoring'
      fullPath: '/app-monitoring'
      preLoaderRoute: typeof AppAppMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wellness/$reportId': {
      id: '/_app/wellness/$reportId'
      path: '/$reportId'
      fullPath: '/wellness/$reportId'
      preLoaderRoute: typeof AppWellnessReportIdRouteImport
      parentRoute: typeof AppWellnessRoute
    }
    '/_app/child/$childId': {
      id: '/_app/child/$childId'
      path: '/child/$childId'
      fullPath: '/child/$childId'
      preLoaderRoute: typeof AppChildChildIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppWellnessRouteChildren {
  AppWellnessReportIdRoute: typeof AppWellnessReportIdRoute
}

const AppWellnessRouteChildren: AppWellnessRouteChildren = {
  AppWellnessReportIdRoute: AppWellnessReportIdRoute,
}

const AppWellnessRouteWithChildren = AppWellnessRoute._addFileChildren(
  AppWellnessRouteChildren,
)

interface AppRouteChildren {
  AppAppMonitoringRoute: typeof AppAppMonitoringRoute
  AppBehaviorAlertsRoute: typeof AppBehaviorAlertsRoute
  AppContractsRoute: typeof AppContractsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFiltersRoute: typeof AppFiltersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWellnessRoute: typeof AppWellnessRouteWithChildren
  AppChildChildIdRoute: typeof AppChildChildIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppMonitoringRoute: AppAppMonitoringRoute,
  AppBehaviorAlertsRoute: AppBehaviorAlertsRoute,
  AppContractsRoute: AppContractsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFiltersRoute: AppFiltersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWellnessRoute: AppWellnessRouteWithChildren,
  AppChildChildIdRoute: AppChildChildIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CTokenRoute: CTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
